### ISSUE TITLE
Invalid project URLs

### ISSUE THREAD

**Issue by maximumspatium** [maximumspatium/jPodRenderer56-maven#1]
These project URLs need to be fixed:
https://github.com/maximumspatium/jPodRenderer56-maven/blob/ca160385c4f76d27dfa4b6da5415b061ab40431b/isCWT/iscwt-5.6.pom#L13
https://github.com/maximumspatium/jPodRenderer56-maven/blob/ca160385c4f76d27dfa4b6da5415b061ab40431b/isFreetype/isfreetype-5.6.pom#L14
https://github.com/maximumspatium/jPodRenderer56-maven/blob/ca160385c4f76d27dfa4b6da5415b061ab40431b/isNativeC/isnativec-5.6.pom#L14
https://github.com/maximumspatium/jPodRenderer56-maven/blob/ca160385c4f76d27dfa4b6da5415b061ab40431b/jPod/jPod-5.6.pom#L14
https://github.com/maximumspatium/jPodRenderer56-maven/blob/ca160385c4f76d27dfa4b6da5415b061ab40431b/jPodRenderer/jPodRenderer-5.6.pom#L14

**Comment by mtraut** [comment]
hi maxim,

added a pull request for the poms that i have finally deployed...

**Comment by maximumspatium** [comment]
Fixed in #3
